alias ll='ls -la'
alias dev='mux start dev'
alias spp='spotify play'
alias sppt='spotify play track'
alias sppa='spotify play album'
alias spps='spotify play song'
alias spstop='spotify stop'
alias mvim="/Applications/MacVim.app/contents/MacOS/MacVim"
alias gac="git add --all && git commit"
